
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app.kubernetes.io/name: web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
  type: LoadBalancer
