apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: us-east1-docker.pkg.dev/bb-demo-project/bb-demo-dev-artifactrepo/web-app-bb-repo:4.0.0 # {"$imagepolicy": "flux-system:my-image-policy"}
          ports:
            - containerPort: 8080
